//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThuongMaiDienTu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ListImage
    {
        public int ImageID { get; set; }
        public string SRC { get; set; }
        public Nullable<int> ProductID { get; set; }
    
        public virtual tb_Product tb_Product { get; set; }
    }
}
