//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThuongMaiDienTu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_Product()
        {
            this.tb_Cart = new HashSet<tb_Cart>();
            this.tb_ListImage = new HashSet<tb_ListImage>();
            this.tb_OrderDetail = new HashSet<tb_OrderDetail>();
            this.tb_ProductComment = new HashSet<tb_ProductComment>();
        }
    
        public int ProductID { get; set; }
        public string Name { get; set; }
        public string Image { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> PromotionPrice { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Description { get; set; }
        public string Detail { get; set; }
        public Nullable<int> CateID { get; set; }
        public int ShopID { get; set; }
        public Nullable<int> BrandID { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual tb_Brand tb_Brand { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Cart> tb_Cart { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_ListImage> tb_ListImage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_OrderDetail> tb_OrderDetail { get; set; }
        public virtual tb_ProductCategory tb_ProductCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_ProductComment> tb_ProductComment { get; set; }
        public virtual tb_Shop tb_Shop { get; set; }
        public virtual tb_Supplier tb_Supplier { get; set; }
    }
}
