//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThuongMaiDienTu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ProductComment
    {
        public int CommentID { get; set; }
        public string Detail { get; set; }
        public Nullable<int> Star { get; set; }
        public int ProductID { get; set; }
        public int CustomerID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual tb_Customer tb_Customer { get; set; }
        public virtual tb_Product tb_Product { get; set; }
    }
}
